INC = /home/system/QuizGame/sprint1/CUT/Code/inc
SRC = /home/system/QuizGame/sprint1/CUT/Code/src
OBJ = /home/system/QuizGame/sprint1/CUT/Code/obj

CFLAGS = -c -g -Wall
LFLAGS = -o
GCC = gcc
CVFLAGS = -Wall -c -g
IFLAGS = -I $(INC)

all : $(BIN)/client

$(OBJ)/client.o : $(SRC)/main.c
        $(GCC) $(CFLAGS) $(SRC)/main.c $(IFLAGS)
        mv *.o/home/system/QuizGame/sprint1/CUT/Code/obj

$(OBJ)/mainmenu.o : $(SRC)/menu.c
        $(GCC) $(CFLAGS) $(SRC)/menu.c $(IFLAGS)
        mv *.o/home/system/QuizGame/sprint1/CUT/Code/obj

$(OBJ)/admin.o : $(SRC)/admin.c
        $(GCC) $(CFLAGS) $(SRC)/admin.c $(IFLAGS)
        mv *.o/home/system/QuizGame/sprint1/CUT/Code/obj

$(OBJ)/coodinator.o : $(SRC)/coordinator.c
        $(GCC) $(CFLAGS) $(SRC)/coordinator.c ($IFLAGS)
        mv *.o/home/system/QuizGame/sprint1/CUT/Code/obj

$(OBJ)/contestant.o : $(SRC)/contestant.c
        $(GCC) $(CFLAGS) $(SRC)/contestant.c $(IFLAGS)
        mv *.o/home/system/Project/QuizGame/sprint1/CUT/Code/obj

$(OBJ)/validations.o : $(SRC)/validations.c
        $(GCC) $(CFLAGS) $(SRC)/validations.c $(IFLAGS)
        mv *.o/home/system/Project/QuizGame/sprint1/CUT/Code/obj


$(BIN)/client : $(OBJ)/client.o $(OBJ)/mainmenu.o $(OBJ)/admin.o $(OBJ)/coordinator.o $(OBJ)/contestant.o $(OBJ)/validations.o
        $(GCC) $(OBJ)/client.o $(OBJ)/mainmenu.o $(OBJ)/admin.o $(OBJ)/coordinator.o $(OBJ)/contestant.o $(OBJ)/validations.o $(LFLAGS) $(BIN)/client